parameters:
  agentName: ''

jobs:

- job: Cleaning_${{ parameters.agentName }}
  displayName: ${{ parameters.agentName }}
  pool:
    name: OryxLinux
    demands:
    - agent.name -equals ${{ parameters.agentName }}
  timeoutInMinutes: 30

  steps:

  - script: echo `pwd`; ls -la; chmod +w ./**/coverage.cobertura.xml
    workingDirectory: $(System.DefaultWorkingDirectory)
    displayName: Clean rogue coverage reports

  - template: _cleanImageCacheTemplate.yml
