
version: '2'

services:
  stickerapp:
    image: stickerapp:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      MONGODB_URL: mongodb://mongo:27017
    ports:
      - 3000:3000
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - 27018:27017