
version: '2'

services:
  stickerapp:
    image: stickerapp:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
      MONGODB_URL: mongodb://mongo:27017
    ports:
      - 3000:3000
      - 5858:5858
    command: node --debug=5858 server/index.js
    ports:
      - 3000:3000
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - 27018:27017