
version: '2'

services:
  stickerapp:
    image: stickerapp:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 5858:5858
    volumes:
      - .:/usr/src/app
    command: node --debug=5858 server/index.js
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - 27017:27017