# File: templates/jobs.yml
jobs:
- job: Job_SetReleaseTag
  displayName: 'Set ReleaseTagName as environment variable'
  pool:
    name: OryxLinux
  steps:
  - task: DownloadPipelineArtifact@2
    inputs:
      targetPath: $(Build.SourcesDirectory)/artifacts
      artifactName: 'releaseTag'

  - script: |
      set -ex
      ls -l $(Build.SourcesDirectory)/artifacts
      ls -l $(Build.SourcesDirectory)/artifacts/releaseTag
      file="$(Build.SourcesDirectory)/artifacts/releaseTag/releaseTag.txt"
      tagName=""
      if [ -f "$file" ]; then
        tagName=`cat $file`
      fi
      echo "##vso[task.setvariable variable=ReleaseTagName;isOutput=true]$tagName"
    displayName: 'Set release tag as environment variable'
    name: setReleaseTag