variables:
  ascName: OryxMCR
  acrName: oryxdevmcr.azurecr.io
  acrProdName: oryxmcr.azurecr.io
  skipComponentGovernanceDetection: true
  artifactsRooDir: '$(Build.SourcesDirectory)/artifacts/images'

jobs:
  - template: templates/_buildAndReleaseBaseImageTemplate.yml
    parameters:
      jobName: Pull_And_Retag_BuildPack_Deps_Images
      scriptPath: ./build/pullAndRetagBuildPackDepsImages.sh
      artifactsFileName: '$(artifactsRooDir)/buildPackDeps-images.txt'

  - template: templates/_buildAndReleaseBaseImageTemplate.yml
    dependsOn: Pull_And_Retag_BuildPack_Deps_Images
    parameters:
      jobName: Build_And_Push_Node_Base_Images_For_Runtime
      scriptPath: ./build/buildRunTimeImageBases.sh
      scriptArgs: node
      artifactsFileName: '$(artifactsRooDir)/node-runtimeimage-bases.txt'

  - template: templates/_buildAndReleaseBaseImageTemplate.yml
    dependsOn: Pull_And_Retag_BuildPack_Deps_Images
    parameters:
      jobName: Build_And_Push_Python_Base_Images_For_Build
      scriptPath: ./build/buildBuildImageBases.sh
      scriptArgs: python
      artifactsFileName: '$(artifactsRooDir)/python-buildimage-bases.txt'

  - template: templates/_buildAndReleaseBaseImageTemplate.yml
    dependsOn: Pull_And_Retag_BuildPack_Deps_Images
    parameters:
      jobName: Build_And_Push_PHP_Base_Images_For_Build
      scriptPath: ./build/buildBuildImageBases.sh
      scriptArgs: php
      artifactsFileName: '$(artifactsRooDir)/php-buildimage-bases.txt'

  - template: templates/_buildAndReleaseBaseImageTemplate.yml
    dependsOn: Pull_And_Retag_BuildPack_Deps_Images
    parameters:
      jobName: Build_And_Push_PHP_Base_Images_For_Runtime
      scriptPath: ./build/buildRunTimeImageBases.sh
      scriptArgs: php
      artifactsFileName: '$(artifactsRooDir)/php-runtimeimage-bases.txt'

  - template: templates/_buildAndReleaseBaseImageTemplate.yml
    parameters:
      jobName: Build_Image_With_YarnCache
      scriptPath: ./build/buildBuildImageBases.sh
      scriptArgs: yarn-cache
      artifactsFileName: '$(artifactsRooDir)/yarn-cache-buildimage-bases.txt'

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - images/runtime/node
    - images/build/python
    - images/build/php
    - images/runtime/php
    - images/build/yarn-cache
    - build/
    - vsts/
