variables:
  ascName: OryxMCR
  acrName: oryxdevmcr.azurecr.io
  acrProdName: oryxmcr.azurecr.io
  skipComponentGovernanceDetection: true
  artifactsRooDir: '$(Build.SourcesDirectory)/artifacts/images'

stages:
- stage: Pull_And_Retag_BuildPack_Deps_Images
  jobs:
    - template: templates/_buildAndReleaseBaseImageTemplate.yml
      parameters:
        jobName: Pull_And_Retag_BuildPack_Deps_Images
        scriptPath: ./build/pullAndRetagBuildPackDepsImages.sh
        artifactFilePath: '$(artifactsRooDir)/buildPackDeps-images.txt'

- stage: Build_Base_Images
  dependsOn: Pull_And_Retag_BuildPack_Deps_Images
  jobs:
    - template: templates/_buildAndReleaseBaseImageTemplate.yml
      parameters:
        jobName: Build_And_Push_Node_Base_Images_For_Runtime
        scriptPath: ./build/buildRunTimeImageBases.sh
        scriptArgs: node
        artifactFilePath: '$(artifactsRooDir)/node-runtimeimage-bases.txt'

    - template: templates/_buildAndReleaseBaseImageTemplate.yml
      parameters:
        jobName: Build_And_Push_Python_Base_Images_For_Build
        scriptPath: ./build/buildBuildImageBases.sh
        scriptArgs: python
        artifactFilePath: '$(artifactsRooDir)/python-buildimage-bases.txt'

    - template: templates/_buildAndReleaseBaseImageTemplate.yml
      parameters:
        jobName: Build_And_Push_PHP_Base_Images_For_Build
        scriptPath: ./build/buildBuildImageBases.sh
        scriptArgs: php
        artifactFilePath: '$(artifactsRooDir)/php-buildimage-bases.txt'

    - template: templates/_buildAndReleaseBaseImageTemplate.yml
      parameters:
        jobName: Build_And_Push_PHP_Base_Images_For_Runtime
        scriptPath: ./build/buildRunTimeImageBases.sh
        scriptArgs: php
        artifactFilePath: '$(artifactsRooDir)/php-runtimeimage-bases.txt'

    - template: templates/_buildAndReleaseBaseImageTemplate.yml
      parameters:
        jobName: Build_Image_With_YarnCache
        scriptPath: ./build/buildBuildImageBases.sh
        scriptArgs: yarn-cache
        artifactFilePath: '$(artifactsRooDir)/yarn-cache-buildimage-bases.txt'

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - images/runtime/node
    - images/build/python
    - images/build/php
    - images/runtime/php
    - images/build/yarn-cache
    - build/
    - vsts/
