queue:
  name: OryxLinux

trigger:
  branches:
    include:
    - master

steps:
- script: |
    echo "##vso[task.setvariable variable=BuildAndTestBuildImages;]true"
    echo "##vso[task.setvariable variable=BuildAndTestRuntimeImages;]true"
    echo "##vso[task.setvariable variable=PushBuildImages;]true"
    echo "##vso[task.setvariable variable=PushRuntimeImages;]true"
    echo "##vso[task.setvariable variable=TestIntegration;]true"
  displayName: 'Set variables'
    
- template: _buildTemplate.yml
