queue:
  name: OryxLinux

trigger: none

steps:
- script: |
    echo "##vso[task.setvariable variable=BuildBuildImages;]true"
    echo "##vso[task.setvariable variable=BuildRuntimeImages;]true"
    echo "##vso[task.setvariable variable=TestIntegration;]true"
    echo "##vso[task.setvariable variable=PushBuildImages;]false"
    echo "##vso[task.setvariable variable=PushRuntimeImages;]false"
    echo "##vso[task.setvariable variable=EmbedBuildContextInImages;]false"
  displayName: 'Set variables'
    
- template: _buildTemplate.yml
