queue:
  name: OryxLinux

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - images/runtime
    - build/
    - src/startupscriptgenerator
    - vsts/

steps:
- script: |
    echo "##vso[task.setvariable variable=BuildAndTestRuntimeImages;]true"
    echo "##vso[task.setvariable variable=PushRuntimeImages;]true"
    echo "##vso[task.setvariable variable=EmbedBuildContextInImages;]true"
  displayName: 'Set variables'
    
- template: _buildTemplate.yml
