queue:
  name: OryxLinux

trigger: none

steps:
- script: |
    echo "##vso[task.setvariable variable=BuildAndTestBuildImages;]true"
    echo "##vso[task.setvariable variable=BuildAndTestRuntimeImages;]true"
    echo "##vso[task.setvariable variable=TestIntegration;]true"
    echo "##vso[task.setvariable variable=EmbedBuildContextInImages;]false"
  displayName: 'Set variables'
    
- template: _buildTemplate.yml


